//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileNumberDiery.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class DieryRecord
    {
        [Display(Name = "ID")]
        public int Person_ID { get; set; }

        [Display(Name = "First Name")]
        [Required(ErrorMessage = "Enter First Name...!")]
        public string Person_FirstName { get; set; }

        [Display(Name = "Last Name")]
        [Required(ErrorMessage = "Enter Last Name...!")]
        public string Person_LastName { get; set; }

        [Display(Name = "Mobile Number")]
        [Required(ErrorMessage = "Enter Mobile Number...!")]
        [MaxLength(10)]
        public string Person_MobileNumber { get; set; }

        [Display(Name = "Whatsup Number")]
        [Required(ErrorMessage = "Enter Whatsup Number...!")]
        [MaxLength(10)]
        public string Person_HomeNumber { get; set; }

        [Display(Name = "City")]
        [Required(ErrorMessage = "Enter City...!")]
        public string Person_City { get; set; }

        [Display(Name = "Tehsil")]
        [Required(ErrorMessage = "Enter Tehsil...!")]
        public string Person_Tehsil { get; set; }

        [Display(Name = "District")]
        [Required(ErrorMessage = "Enter District...!")]
        public string Person_District { get; set; }

        [Display(Name = "State")]
        [Required(ErrorMessage = "Enter State...!")]
        public string Person_State { get; set; }

        [Display(Name = "Catagery")]
        [Required(ErrorMessage = "Select Atleast One Item ...!")]
        public Nullable<int> R_FK_CATID { get; set; }
    
        public virtual TBL_CATEGORY TBL_CATEGORY { get; set; }
    }
}
