//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileNumberDiery.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TBL_CATEGORY
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_CATEGORY()
        {
            this.DieryRecords = new HashSet<DieryRecord>();
        }
    
        public int CAT_ID { get; set; }
        [Display(Name = "Catagery")]
        [Required(ErrorMessage = "Create Which Side You Want (exp:- Home/Business/Friends..etc)...!")]
        public string CAT_NAME { get; set; }
        public Nullable<int> CAT_PK_ADID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DieryRecord> DieryRecords { get; set; }
        public virtual TBL_ADMIN TBL_ADMIN { get; set; }
    }
}
